"""Curated movie-quote "wisdom" for the bot's `What is thy wisdom` easter egg.

Raw quote text only — no quotation marks, no character names, no film titles.
Deliberately eclectic: blockbuster-iconic through deep-cut obscure, classic
through brand-new, US through world cinema, and the cult / arthouse / horror /
noir register you'd catch at Suns, AFI Silver, the NGA, or Alamo. Add freely.
"""

QUOTES = [
    # ── Iconic / pop-culture ──────────────────────────────────────────────────
    "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.",
    "Every man dies. Not every man really lives.",
    "What we do in life echoes in eternity.",
    "Get busy living, or get busy dying.",
    "The greatest trick the devil ever pulled was convincing the world he didn't exist.",
    "Why so serious?",
    "You're gonna need a bigger boat.",
    "I'm going to make him an offer he can't refuse.",
    "There's no place like home.",
    "Wax on, wax off.",
    "Just keep swimming.",
    "To infinity and beyond.",
    "With great power comes great responsibility.",
    "I feel the need — the need for speed.",
    "Say hello to my little friend.",
    "You had me at hello.",
    "Houston, we have a problem.",
    "Hasta la vista, baby.",
    "I'll be back.",
    "There is no spoon.",
    "Do, or do not. There is no try.",
    "Now, I am become Death, the destroyer of worlds.",
    "Roads? Where we're going we don't need roads.",
    "Snap out of it.",
    "Carpe diem. Seize the day, boys. Make your lives extraordinary.",
    "The night is darkest just before the dawn.",
    "It's not who I am underneath, but what I do that defines me.",
    "A man's got to know his limitations.",
    "You talking to me?",
    "Here's looking at you, kid.",
    "Round up the usual suspects.",
    "Of all the gin joints in all the towns in all the world, she walks into mine.",

    # ── Noir / classic Hollywood ──────────────────────────────────────────────
    "The stuff that dreams are made of.",
    "I'm ready for my close-up.",
    "Forget it. It's just the way things are.",
    "You know how to whistle, don't you? You just put your lips together and blow.",
    "In Italy for thirty years they had warfare, terror, murder and bloodshed, but they produced the Renaissance.",
    "I never drink water because of the disgusting things that fish do in it.",
    "Fasten your seatbelts. It's going to be a bumpy night.",
    "I want the truth. You can't handle the truth.",
    "Nobody's perfect.",
    "Well, nobody's perfect, and that includes me.",
    "We rob banks.",
    "A boy's best friend is his mother.",
    "We all go a little mad sometimes.",
    "I could have been a contender. I could have been somebody.",
    "Made it, Ma. Top of the world.",
    "Greed, for lack of a better word, is good.",
    "The only thing standing between you and your goal is the story you keep telling yourself.",
    "As God is my witness, I'll never be hungry again.",
    "Frankly, I don't give a damn.",
    "Louis, I think this is the beginning of a beautiful friendship.",

    # ── Sci-fi ────────────────────────────────────────────────────────────────
    "All those moments will be lost in time, like tears in rain.",
    "More human than human is our motto.",
    "I've seen things you people wouldn't believe.",
    "Open the pod bay doors.",
    "My God, it's full of stars.",
    "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.",
    "Nature is a mutable cloud which is always and never the same.",
    "Fear is the mind-killer.",
    "The spice must flow.",
    "Resistance is futile.",
    "The needs of the many outweigh the needs of the few.",
    "Game over, man.",
    "In space, no one can hear you scream.",
    "We are the music makers, and we are the dreamers of dreams.",
    "Reality is that which, when you stop believing in it, doesn't go away.",
    "Nothing is written.",
    "The truth is out there.",
    "Perhaps the earth is heaven, and we are already dead, and the only hell is the one we build for each other.",

    # ── Cult / weird ──────────────────────────────────────────────────────────
    "The first rule is you do not talk about it.",
    "It's only after we've lost everything that we're free to do anything.",
    "This is your life and it's ending one minute at a time.",
    "The Dude abides.",
    "That rug really tied the room together.",
    "Sometimes you eat the bar, and sometimes, well, the bar eats you.",
    "I'm a plate of shrimp away from a black hole.",
    "The more you drive, the less intelligent you are.",
    "You can't hurt me, I'm already dead.",
    "I did not hit her, it's not true, it's bullshit, I did not hit her. I did naht. Oh hi.",
    "You're tearing me apart.",
    "Every day, once a day, give yourself a present.",
    "Fire walk with me.",
    "The owls are not what they seem.",
    "I want to be scared. I want to be terrified. I want to be filled with wonder.",
    "A lot of people don't realize what's really going on. They view life as a bunch of unconnected incidents and things.",
    "Wake up. You have to wake up.",
    "Every living creature on earth dies alone.",
    "We are the all-singing, all-dancing crap of the world.",
    "Don't dream it, be it.",
    "L-I-V-E. Live. Otherwise you got nothing to talk about in the locker room.",
    "I haven't lived a day since. Neither have you.",
    "You have to go on living, so live.",

    # ── Horror ────────────────────────────────────────────────────────────────
    "Do you know what's out there in the world? Nothing. Absolutely nothing.",
    "We have such sights to show you.",
    "It's alive. It's moving. It's alive, it's alive, it's alive.",
    "Whatever you do, don't fall asleep.",
    "They're here.",
    "Sometimes dead is better.",
    "One, two, he's coming for you.",
    "A census taker once tried to test me. I ate his liver with some fava beans.",
    "The power of Christ compels you.",
    "When there's no more room in hell, the dead will walk the earth.",
    "I see dead people.",
    "Be afraid. Be very afraid.",
    "Death is but a door. Time is but a window. I'll be back.",
    "Man is the warmest place to hide.",
    "Trust is a tough thing to come by these days.",
    "You've got red on you.",

    # ── World cinema (translated) ─────────────────────────────────────────────
    "You know what kind of plan never fails? No plan at all.",
    "Once you overcome the one-inch-tall barrier of subtitles, you will be introduced to so many more amazing films.",
    "Life is a shipwreck, but we must not forget to sing in the lifeboats.",
    "Times are bad. Children no longer obey their parents, and everyone is writing a book.",
    "The past is like a foreign country. It's not that people do things differently there. They just remember them differently.",
    "Life is beautiful.",
    "The wound is the place where the light enters you.",
    "We don't need other worlds. We need mirrors.",
    "Happiness is only real when shared.",
    "Nostalgia is a dangerous form of comparison.",
    "The bad guys can't win. Never. Otherwise the story would be immoral.",
    "Fighting monsters, take care not to become one.",
    "Beauty is in the eye of the beholder, and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.",
    "Once you know how to die, you know how to live.",
    "Even the darkest night will end and the sun will rise.",
    "A single flower makes no garland.",
    "When you have eliminated the impossible, whatever remains must be the truth.",
    "The only true wisdom is in knowing you know nothing.",
    "Nothing here is what it seems.",
    "You cannot see the whole sky through a bamboo tube.",
    "In the depth of winter, I finally learned that within me there lay an invincible summer.",
    "Everyone you meet is fighting a battle you know nothing about. Be kind. Always.",

    # ── Arthouse / new ────────────────────────────────────────────────────────
    "I drink your milkshake.",
    "I'm finished.",
    "What's the most you ever lost on a coin toss?",
    "Call it, friendo.",
    "You need to be careful. There is greatness in you, but you have to want it.",
    "The world is a very malleable place.",
    "I have tried to be a nice guy. I really have.",
    "There is no such thing as no context. There is only the context you don't yet see.",
    "The end is built into the beginning.",
    "Everything is the same distance from the sun.",
    "In another life, I would have really liked just doing laundry and taxes with you.",
    "Nothing matters. No point being anything but kind.",
    "So, I know how you feel. Because I don't know how you feel.",
    "Under here you just get colder and colder, and then you die.",
    "We're all just floating in space, trying not to be forgotten.",
    "The bird a nest, the spider a web, man friendship.",
    "How the light gets in is through the crack.",
    "There is nothing outside. There is only this, right now, and it is enough.",

    # ── Comedy / warm ─────────────────────────────────────────────────────────
    "As you wish.",
    "Have fun storming the castle.",
    "Life is like a box of chocolates. You never know what you're gonna get.",
    "Big things have small beginnings.",
    "Be excellent to each other.",
    "I don't want to survive. I want to live.",
    "The greatest thing you'll ever learn is just to love and be loved in return.",
    "You is kind. You is smart. You is important.",
    "It is not our abilities that show what we truly are. It is our choices.",
    "Not all those who wander are lost.",
    "Even the smallest person can change the course of the future.",
    "There's some good in this world, and it's worth fighting for.",
    "I'm also just a girl, standing in front of a boy, asking him to love her.",
    "Adventure is out there.",
    "The flower that blooms in adversity is the most rare and beautiful of all.",
    "A person is a person, no matter how small.",
    "Today is the youngest you'll ever be. Enjoy it while it lasts.",
    "You must find a way to carry the good things forward.",
]
