"""Curated movie-quote "wisdom" for the bot.

Raw lines of real film dialogue (best-effort verbatim), as actually delivered —
character names, details, and profanity intact, from the silly and absurd to the
very R-rated, with longer iconic monologues mixed in. Lines are chosen to work as
a reaction/retort in a live chat (the bot drops them mid-conversation), so they
lean recognizable and context-rich rather than vague one-liners. Each carries a
comment attributing the film (and character, where known). No attribution text is
shown to users; the line stands alone. A few well-known poster *taglines* are
included and marked "(tagline)". If any line reads wrong, fix the string and its
comment together. Add freely.
"""

QUOTES = [
    # ── Iconic / pop-culture ──────────────────────────────────────────────────
    "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.",  # Ferris Bueller's Day Off (Ferris)
    "Frankly, my dear, I don't give a damn.",  # Gone with the Wind (Rhett Butler)
    "After all, tomorrow is another day!",  # Gone with the Wind (Scarlett O'Hara)
    "Here's looking at you, kid.",  # Casablanca (Rick)
    "We'll always have Paris.",  # Casablanca (Rick)
    "Louis, I think this is the beginning of a beautiful friendship.",  # Casablanca (Rick)
    "Of all the gin joints in all the towns in all the world, she walks into mine.",  # Casablanca (Rick)
    "You had me at hello.",  # Jerry Maguire (Dorothy)
    "Show me the money!",  # Jerry Maguire (Rod Tidwell)
    "Help me help you.",  # Jerry Maguire (Jerry)
    "You complete me.",  # Jerry Maguire (Jerry)
    "I'm gonna make him an offer he can't refuse.",  # The Godfather (Michael Corleone)
    "It's not personal, Sonny. It's strictly business.",  # The Godfather (Michael Corleone)
    "Leave the gun. Take the cannoli.",  # The Godfather (Clemenza)
    "Keep your friends close, but your enemies closer.",  # The Godfather Part II (Michael Corleone)
    "You wanna play rough? Okay. Say hello to my little friend!",  # Scarface (Tony Montana)
    "The World Is Yours.",  # Scarface (the blimp/statue motif)
    "Say good night to the bad guy!",  # Scarface (Tony Montana)
    "Nobody puts Baby in a corner.",  # Dirty Dancing (Johnny)
    "Toto, I've a feeling we're not in Kansas anymore.",  # The Wizard of Oz (Dorothy)
    "Pay no attention to that man behind the curtain!",  # The Wizard of Oz (the Wizard)
    "There's no place like home.",  # The Wizard of Oz (Dorothy)
    "I'll have what she's having.",  # When Harry Met Sally... (a diner customer)
    "You can't handle the truth! Son, we live in a world that has walls, and those walls have to be guarded by men with guns.",  # A Few Good Men (Col. Jessup)
    "You want me on that wall, you need me on that wall.",  # A Few Good Men (Col. Jessup)
    "Wax on, wax off.",  # The Karate Kid (Mr. Miyagi)
    "Run, Forrest, run!",  # Forrest Gump (Jenny)
    "Stupid is as stupid does.",  # Forrest Gump (Forrest)
    "My mama always said life was like a box of chocolates. You never know what you're gonna get.",  # Forrest Gump (Forrest)
    "There's no crying in baseball!",  # A League of Their Own (Jimmy Dugan)
    "You're killing me, Smalls.",  # The Sandlot (Ham)
    "If you build it, he will come.",  # Field of Dreams (the whispering voice)
    "I'm the king of the world!",  # Titanic (Jack)
    "I'm walkin' here! I'm walkin' here!",  # Midnight Cowboy (Ratso Rizzo)
    "Why so serious?",  # The Dark Knight (the Joker)
    "You either die a hero, or you live long enough to see yourself become the villain.",  # The Dark Knight (Harvey Dent)
    "Some men just want to watch the world burn.",  # The Dark Knight (Alfred)
    "It's not who I am underneath, but what I do that defines me.",  # Batman Begins (Bruce/Rachel)
    "You're gonna need a bigger boat.",  # Jaws (Brody)
    "You go in the cage. Cage goes in the water. You go in the water. Shark's in the water. Our shark.",  # Jaws (Quint)
    "Smile, you son of a bitch!",  # Jaws (Brody)
    "Houston, we have a problem.",  # Apollo 13 (Jim Lovell)
    "Failure is not an option.",  # Apollo 13 (Gene Kranz)
    "Carpe diem. Seize the day, boys. Make your lives extraordinary.",  # Dead Poets Society (John Keating)
    "What we do in life echoes in eternity.",  # Gladiator (Maximus)
    "Are you not entertained? Are you not entertained? Is this not why you are here?",  # Gladiator (Maximus)
    "My name is Maximus Decimus Meridius, commander of the Armies of the North, General of the Felix Legions, loyal servant to the true emperor, Marcus Aurelius. Father to a murdered son, husband to a murdered wife. And I will have my vengeance, in this life or the next.",  # Gladiator (Maximus)
    "This is Sparta!",  # 300 (Leonidas)
    "Tonight, we dine in hell!",  # 300 (Leonidas)
    "They may take our lives, but they'll never take our freedom!",  # Braveheart (William Wallace)
    "A man's got to know his limitations.",  # Magnum Force (Harry Callahan)
    "Go ahead, make my day.",  # Sudden Impact (Harry Callahan)
    "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?",  # Dirty Harry (Harry Callahan)
    "You talkin' to me? You talkin' to me? You talkin' to me? Then who the hell else are you talkin' to? You talkin' to me? Well, I'm the only one here.",  # Taxi Driver (Travis Bickle)
    "I love the smell of napalm in the morning. You know, one time we had a hill bombed for twelve hours. And the smell, you know, that gasoline smell, the whole hill — smelled like victory.",  # Apocalypse Now (Lt. Col. Kilgore)
    "The horror... the horror.",  # Apocalypse Now (Kurtz)
    "I want you to get up right now, and go to the window, open it, and stick your head out and yell: 'I'm as mad as hell, and I'm not going to take this anymore!'",  # Network (Howard Beale)
    "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.",  # Rocky Balboa (Rocky Balboa)
    "Get busy living, or get busy dying.",  # The Shawshank Redemption (Andy/Red)
    "Hope is a good thing, maybe the best of things, and no good thing ever dies.",  # The Shawshank Redemption (Andy)
    "I will look for you, I will find you, and I will kill you.",  # Taken (Bryan Mills)

    # ── Noir / classic Hollywood ──────────────────────────────────────────────
    "The stuff that dreams are made of.",  # The Maltese Falcon (Sam Spade)
    "All right, Mr. DeMille, I'm ready for my close-up.",  # Sunset Boulevard (Norma Desmond)
    "I am big. It's the pictures that got small.",  # Sunset Boulevard (Norma Desmond)
    "We didn't need dialogue. We had faces!",  # Sunset Boulevard (Norma Desmond)
    "Fasten your seatbelts. It's going to be a bumpy night.",  # All About Eve (Margo Channing)
    "Nobody's perfect.",  # Some Like It Hot (Osgood, last line)
    "We rob banks.",  # Bonnie and Clyde (Clyde)
    "I coulda been a contender. I coulda been somebody, instead of a bum, which is what I am.",  # On the Waterfront (Terry Malloy)
    "Made it, Ma! Top of the world!",  # White Heat (Cody Jarrett)
    "As God is my witness, I'll never be hungry again.",  # Gone with the Wind (Scarlett O'Hara)
    "You know how to whistle, don't you, Steve? You just put your lips together and blow.",  # To Have and Have Not (Marie 'Slim')
    "I killed him for money and for a woman. I didn't get the money and I didn't get the woman.",  # Double Indemnity (Walter Neff)
    "What we've got here is failure to communicate.",  # Cool Hand Luke (the Captain)
    "The greatest trick the Devil ever pulled was convincing the world he didn't exist.",  # The Usual Suspects (Verbal Kint)
    "Put that coffee down! Coffee's for closers only.",  # Glengarry Glen Ross (Blake)
    "Don't let yourself get attached to anything you are not willing to walk out on in thirty seconds flat if you feel the heat around the corner.",  # Heat (Neil McCauley)
    "Forget it, Jake. It's Chinatown.",  # Chinatown (Lawrence Walsh)
    "Greed, for lack of a better word, is good. Greed is right. Greed works.",  # Wall Street (Gordon Gekko)
    "Attica! Attica!",  # Dog Day Afternoon (Sonny)
    "Rosebud.",  # Citizen Kane (Charles Foster Kane)

    # ── Sci-fi / fantasy ──────────────────────────────────────────────────────
    "May the Force be with you.",  # Star Wars: A New Hope
    "No, I am your father.",  # The Empire Strikes Back (Darth Vader)
    "Do. Or do not. There is no try.",  # The Empire Strikes Back (Yoda)
    "I find your lack of faith disturbing.",  # Star Wars: A New Hope (Darth Vader)
    "These aren't the droids you're looking for.",  # Star Wars: A New Hope (Obi-Wan)
    "It's a trap!",  # Return of the Jedi (Admiral Ackbar)
    "Never tell me the odds.",  # The Empire Strikes Back (Han Solo)
    "Laugh it up, fuzzball.",  # The Empire Strikes Back (Han Solo)
    "I have a bad feeling about this.",  # Star Wars (recurring)
    "So this is how liberty dies. With thunderous applause.",  # Revenge of the Sith (Padmé)
    "Hello there.",  # Star Wars (Obi-Wan Kenobi)
    "There is no spoon.",  # The Matrix (Spoon Boy/Neo)
    "I know kung fu.",  # The Matrix (Neo)
    "What is real? How do you define real?",  # The Matrix (Morpheus)
    "There's a difference between knowing the path and walking the path.",  # The Matrix (Morpheus)
    "Welcome to the desert of the real.",  # The Matrix (Morpheus)
    "Dodge this.",  # The Matrix (Trinity)
    "I'll be back.",  # The Terminator (the Terminator)
    "Come with me if you want to live.",  # The Terminator / T2 (Reese/Terminator)
    "I need your clothes, your boots, and your motorcycle.",  # Terminator 2: Judgment Day (the Terminator)
    "Hasta la vista, baby.",  # Terminator 2: Judgment Day (the Terminator)
    "Get away from her, you bitch!",  # Aliens (Ripley)
    "Game over, man! Game over!",  # Aliens (Hudson)
    "I say we take off and nuke the entire site from orbit. It's the only way to be sure.",  # Aliens (Ripley)
    "In space, no one can hear you scream.",  # Alien (tagline)
    "I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. All those moments will be lost in time, like tears in rain. Time to die.",  # Blade Runner (Roy Batty)
    "Open the pod bay doors, HAL.",  # 2001: A Space Odyssey (Dave Bowman)
    "My God, it's full of stars.",  # 2010: The Year We Make Contact (Bowman)
    "Now I am become Death, the destroyer of worlds.",  # Oppenheimer (J. Robert Oppenheimer)
    "Life, uh, finds a way.",  # Jurassic Park (Ian Malcolm)
    "Hold onto your butts.",  # Jurassic Park (Ray Arnold)
    "Great Scott!",  # Back to the Future (Doc Brown)
    "1.21 gigawatts!",  # Back to the Future (Doc Brown)
    "Roads? Where we're going, we don't need roads.",  # Back to the Future (Doc Brown)
    "Nobody calls me chicken.",  # Back to the Future Part II (Marty McFly)
    "E.T. phone home.",  # E.T. the Extra-Terrestrial (E.T.)
    "Take your stinking paws off me, you damned dirty ape!",  # Planet of the Apes (Taylor)
    "Welcome to Earth.",  # Independence Day (Capt. Steven Hiller)
    "The needs of the many outweigh the needs of the few.",  # Star Trek II: The Wrath of Khan (Spock)
    "Live long and prosper.",  # Star Trek (Spock)
    "He slimed me.",  # Ghostbusters (Peter Venkman)
    "Back off, man. I'm a scientist.",  # Ghostbusters (Peter Venkman)
    "When someone asks if you're a god, you say yes!",  # Ghostbusters (Winston Zeddemore)
    "Human sacrifice, dogs and cats living together — mass hysteria!",  # Ghostbusters (Peter Venkman)
    "A person is smart. People are dumb, panicky, dangerous animals, and you know it.",  # Men in Black (Agent K)
    "Get your ass to Mars.",  # Total Recall (Douglas Quaid)
    "Consider that a divorce.",  # Total Recall (Douglas Quaid)
    "Dead or alive, you're coming with me.",  # RoboCop (RoboCop)
    "May the Schwartz be with you.",  # Spaceballs (Yogurt)
    "I am your father's brother's nephew's cousin's former roommate.",  # Spaceballs (Dark Helmet)
    "Never give up, never surrender!",  # Galaxy Quest (Jason Nesmith)
    "One does not simply walk into Mordor.",  # The Fellowship of the Ring (Boromir)
    "You shall not pass!",  # The Fellowship of the Ring (Gandalf)
    "My precious.",  # The Lord of the Rings (Gollum)
    "Even the smallest person can change the course of the future.",  # The Fellowship of the Ring (Galadriel)
    "All we have to decide is what to do with the time that is given us.",  # The Fellowship of the Ring (Gandalf)

    # ── Action ────────────────────────────────────────────────────────────────
    "Yippee-ki-yay, motherfucker.",  # Die Hard (John McClane)
    "Now I have a machine gun. Ho-ho-ho.",  # Die Hard (McClane's message on a corpse)
    "Welcome to the party, pal!",  # Die Hard (John McClane)
    "Get to the chopper!",  # Predator (Dutch)
    "If it bleeds, we can kill it.",  # Predator (Dutch)
    "You're one ugly motherfucker.",  # Predator (Dutch)
    "I ain't got time to bleed.",  # Predator (Blain)
    "Let off some steam, Bennett.",  # Commando (John Matrix)
    "Remember, Sully, when I promised to kill you last? I lied.",  # Commando (John Matrix)
    "Bond. James Bond.",  # Dr. No (James Bond)
    "A martini. Shaken, not stirred.",  # Goldfinger (James Bond)
    "Do you expect me to talk? No, Mr. Bond, I expect you to die.",  # Goldfinger (Bond/Goldfinger)
    "I'm your huckleberry.",  # Tombstone (Doc Holliday)

    # ── Cult / weird ──────────────────────────────────────────────────────────
    "The first rule of Fight Club is: you do not talk about Fight Club.",  # Fight Club (Tyler Durden)
    "It's only after we've lost everything that we're free to do anything.",  # Fight Club (Tyler Durden)
    "You are not your job. You're not how much money you have in the bank. You're not the car you drive. You're not the contents of your wallet. You are the all-singing, all-dancing crap of the world.",  # Fight Club (Tyler Durden)
    "The Dude abides.",  # The Big Lebowski (the Dude)
    "That rug really tied the room together.",  # The Big Lebowski (the Dude)
    "Yeah, well, that's just, like, your opinion, man.",  # The Big Lebowski (the Dude)
    "This aggression will not stand, man.",  # The Big Lebowski (the Dude)
    "Say what you want about the tenets of National Socialism, Dude, at least it's an ethos.",  # The Big Lebowski (Walter)
    "Shut the fuck up, Donny.",  # The Big Lebowski (Walter)
    "Nobody fucks with the Jesus.",  # The Big Lebowski (Jesus Quintana)
    "You're entering a world of pain.",  # The Big Lebowski (Walter)
    "Mark it zero!",  # The Big Lebowski (Walter)
    "This is what happens when you find a stranger in the Alps!",  # The Big Lebowski (Walter, TV edit)
    "Careful, man, there's a beverage here!",  # The Big Lebowski (the Dude)
    "I did not hit her, it's not true, it's bullshit, I did not hit her, I did naht. Oh hi Mark.",  # The Room (Johnny)
    "You're tearing me apart, Lisa!",  # The Room (Johnny)
    "Fire walk with me.",  # Twin Peaks: Fire Walk with Me
    "Don't dream it, be it.",  # The Rocky Horror Picture Show (Frank-N-Furter)
    "We are the music makers, and we are the dreamers of dreams.",  # Willy Wonka & the Chocolate Factory (Wonka)
    "Try not to suck any dick on the way through the parking lot!",  # Clerks (Randal)

    # ── Horror ────────────────────────────────────────────────────────────────
    "They're coming to get you, Barbara.",  # Night of the Living Dead (Johnny)
    "When there's no more room in hell, the dead will walk the earth.",  # Dawn of the Dead (Peter)
    "We have such sights to show you.",  # Hellraiser (Pinhead)
    "It's alive! It's alive! In the name of God, now I know what it feels like to be God!",  # Frankenstein 1931 (Henry Frankenstein)
    "Whatever you do, don't fall asleep.",  # A Nightmare on Elm Street (tagline)
    "They're here.",  # Poltergeist (Carol Anne)
    "This house is clean.",  # Poltergeist (Tangina)
    "Sometimes dead is better.",  # Pet Sematary (Jud Crandall)
    "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.",  # The Silence of the Lambs (Hannibal Lecter)
    "I'm having an old friend for dinner.",  # The Silence of the Lambs (Hannibal Lecter)
    "The power of Christ compels you!",  # The Exorcist (Fr. Karras/Merrin)
    "Your mother sucks cocks in hell!",  # The Exorcist (the demon/Regan)
    "I see dead people.",  # The Sixth Sense (Cole)
    "Be afraid. Be very afraid.",  # The Fly 1986 (Veronica)
    "Man is the warmest place to hide.",  # The Thing 1982 (tagline)
    "You've got red on you.",  # Shaun of the Dead (Ed)
    "We all float down here.",  # It (Pennywise)
    "Do you like scary movies?",  # Scream (Ghostface)
    "What's your favorite scary movie?",  # Scream (Ghostface)
    "Here's Johnny!",  # The Shining (Jack Torrance)
    "All work and no play makes Jack a dull boy.",  # The Shining (Jack's typed pages)
    "Redrum.",  # The Shining (Danny)
    "Come and play with us, Danny. Forever, and ever, and ever.",  # The Shining (the Grady twins)
    "We all go a little mad sometimes.",  # Psycho (Norman Bates)
    "A boy's best friend is his mother.",  # Psycho (Norman Bates)
    "Listen to them, the children of the night. What music they make.",  # Dracula 1931 (Count Dracula)
    "Hi, I'm Chucky. Wanna play?",  # Child's Play (Chucky)
    "Get out.",  # The Amityville Horror (the house)
    "Klaatu barada nikto.",  # The Day the Earth Stood Still (Klaatu)

    # ── World cinema (translated) ─────────────────────────────────────────────
    "You know what kind of plan never fails? No plan at all.",  # Parasite (Ki-taek)
    "She's rich, but still nice. Not 'still nice.' Nice because she's rich.",  # Parasite (Chung-sook)
    "Life isn't like in the movies. Life is much harder.",  # Cinema Paradiso (Alfredo)
    "Times are hard for dreamers.",  # Amélie (narration)
    "A kid? I smoke, I snort. I've killed and robbed. I'm a man.",  # City of God (Steak with Fries)
    "Once you've met someone, you never really forget them.",  # Spirited Away (Zeniba)
    "It's not how you fall that matters. It's how you land.",  # La Haine (closing narration)
    "The farmers have won. Not us.",  # Seven Samurai (Kambei)
    "Happiness is only real when shared.",  # Into the Wild (Christopher McCandless)

    # ── Arthouse / modern ─────────────────────────────────────────────────────
    "I drink your milkshake! I drink it up!",  # There Will Be Blood (Daniel Plainview)
    "I have a competition in me. I want no one else to succeed. I hate most people.",  # There Will Be Blood (Daniel Plainview)
    "I'm finished.",  # There Will Be Blood (Daniel Plainview, last line)
    "What's the most you ever lost on a coin toss?",  # No Country for Old Men (Anton Chigurh)
    "You need to call it. I can't call it for you. It wouldn't be fair.",  # No Country for Old Men (Anton Chigurh)
    "What's in the box?!",  # Se7en (Det. David Mills)
    "I'm not sure I agree with you a hundred percent on your police work there, Lou.",  # Fargo (Marge Gunderson)
    "There's more to life than a little money, you know. Don'tcha know that?",  # Fargo (Marge Gunderson)
    "Royale with cheese.",  # Pulp Fiction (Vincent Vega)
    "That's a pretty fuckin' good milkshake.",  # Pulp Fiction (Vincent Vega)
    "I don't tip because society says I have to.",  # Reservoir Dogs (Mr. Pink)
    "Not quite my tempo.",  # Whiplash (Terence Fletcher)
    "Were you rushing, or were you dragging?",  # Whiplash (Terence Fletcher)
    "There are no two words in the English language more harmful than 'good job.'",  # Whiplash (Fletcher)
    "This is how I win.",  # Uncut Gems (Howard Ratner)
    "A million dollars isn't cool. You know what's cool? A billion dollars.",  # The Social Network (Sean Parker)
    "The past is just a story we tell ourselves.",  # Her (Samantha)
    "In moonlight, black boys look blue.",  # Moonlight (Juan)
    "Do all lovers feel they're inventing something?",  # Portrait of a Lady on Fire (Héloïse)
    "Rudeness is merely the expression of fear.",  # The Grand Budapest Hotel (M. Gustave)
    "You see, there are still faint glimmers of civilization left in this barbaric slaughterhouse that was once known as humanity.",  # The Grand Budapest Hotel (M. Gustave)
    "In another life, I would have really liked just doing laundry and taxes with you.",  # Everything Everywhere All at Once (Evelyn)
    "The only thing I know is that we have to be kind.",  # Everything Everywhere All at Once (Waymond)
    "Why'd ya spill yer beans?",  # The Lighthouse (Thomas Wake)
    "You mustn't be afraid to dream a little bigger, darling.",  # Inception (Eames)
    "We accept the reality of the world with which we're presented.",  # The Truman Show (Christof)

    # ── Comedy / warm ─────────────────────────────────────────────────────────
    "As you wish.",  # The Princess Bride (Westley)
    "Have fun storming the castle!",  # The Princess Bride (Miracle Max)
    "Inconceivable!",  # The Princess Bride (Vizzini)
    "You keep using that word. I do not think it means what you think it means.",  # The Princess Bride (Inigo Montoya)
    "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.",  # The Princess Bride (Inigo Montoya)
    "Life is pain, Highness. Anyone who says differently is selling something.",  # The Princess Bride (Westley)
    "Snap out of it!",  # Moonstruck (Loretta Castorini)
    "O Captain! My Captain!",  # Dead Poets Society (the students, quoting Whitman)
    "I'm also just a girl, standing in front of a boy, asking him to love her.",  # Notting Hill (Anna Scott)
    "It is our choices, Harry, that show what we truly are, far more than our abilities.",  # Harry Potter and the Chamber of Secrets (Dumbledore)
    "You is kind. You is smart. You is important.",  # The Help (Aibileen)
    "There's some good in this world, Mr. Frodo, and it's worth fighting for.",  # The Two Towers (Samwise)
    "Ohana means family. Family means nobody gets left behind or forgotten.",  # Lilo & Stitch (Lilo)
    "Hakuna matata. It means no worries.",  # The Lion King (Timon)
    "A person's a person, no matter how small.",  # Horton Hears a Who! (Horton)
    "You sit on a throne of lies.",  # Elf (Buddy)
    "Keep the change, ya filthy animal.",  # Home Alone (the film-within-a-film gangster)
    "He's not the Messiah, he's a very naughty boy!",  # Life of Brian (Brian's mother)
    "Blessed are the cheesemakers.",  # Life of Brian (a listener at the Sermon on the Mount)
    "Help! Help! I'm being repressed!",  # Monty Python and the Holy Grail (Dennis)
    "'Tis but a scratch.",  # Monty Python and the Holy Grail (Black Knight)
    "It's just a flesh wound.",  # Monty Python and the Holy Grail (Black Knight)
    "We are the Knights Who Say Ni!",  # Monty Python and the Holy Grail (the Knights)
    "Bring out your dead!",  # Monty Python and the Holy Grail (the cart driver)
    "I fart in your general direction.",  # Monty Python and the Holy Grail (French Taunter)
    "Your mother was a hamster and your father smelt of elderberries.",  # Monty Python and the Holy Grail (French Taunter)
    "Now go away, or I shall taunt you a second time!",  # Monty Python and the Holy Grail (French Taunter)

    # ── Crude / silly / R-rated ───────────────────────────────────────────────
    "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men.",  # Pulp Fiction (Jules, Ezekiel 25:17)
    "English, motherfucker, do you speak it?",  # Pulp Fiction (Jules)
    "Say 'what' again. Say 'what' again, I dare you, I double dare you, motherfucker.",  # Pulp Fiction (Jules)
    "Zed's dead, baby. Zed's dead.",  # Pulp Fiction (Butch)
    "This is a tasty burger!",  # Pulp Fiction (Jules)
    "But I'm funny how? I mean, funny like I'm a clown? I amuse you? I make you laugh? I'm here to fuckin' amuse you?",  # Goodfellas (Tommy DeVito)
    "Now go home and get your fuckin' shinebox.",  # Goodfellas (Billy Batts)
    "As far back as I can remember, I always wanted to be a gangster.",  # Goodfellas (Henry Hill)
    "In this country, you gotta make the money first. Then when you get the money, you get the power.",  # Scarface (Tony Montana)
    "Maybe that's what hell is: the entire rest of eternity spent in fuckin' Bruges.",  # In Bruges (Ray)
    "I'm not fuckin' leaving.",  # The Wolf of Wall Street (Jordan Belfort)
    "Move the money from your client's pocket into your pocket.",  # The Wolf of Wall Street (Mark Hanna)
    "You know when you hear girls say, 'I was so shitfaced last night, I shouldn't have fucked that guy'? We could be that mistake!",  # Superbad (Seth)
    "McLovin? What kind of a stupid name is that?",  # Superbad (Seth)
    "Did we just become best friends? Yup!",  # Step Brothers (Brennan & Dale)
    "There's so many activities!",  # Step Brothers (Brennan)
    "Boats 'n hoes.",  # Step Brothers (Brennan & Dale)
    "I'm kind of a big deal.",  # Anchorman (Ron Burgundy)
    "Milk was a bad choice.",  # Anchorman (Ron Burgundy)
    "I'm in a glass case of emotion!",  # Anchorman (Ron Burgundy)
    "Great Odin's raven!",  # Anchorman (Ron Burgundy)
    "Sixty percent of the time, it works every time.",  # Anchorman (Brian Fantana)
    "I love lamp.",  # Anchorman (Brick Tamland)
    "You stay classy, San Diego.",  # Anchorman (Ron Burgundy)
    "Boy, that escalated quickly. I mean, that really got out of hand fast.",  # Anchorman (Ron Burgundy)
    "Shake and bake!",  # Talladega Nights (Ricky Bobby & Cal)
    "If you ain't first, you're last.",  # Talladega Nights (Reese Bobby)
    "Dear Lord baby Jesus, we thank you so much for this bountiful harvest of Domino's, KFC, and the always delicious Taco Bell.",  # Talladega Nights (Ricky Bobby)
    "So you're telling me there's a chance.",  # Dumb and Dumber (Lloyd)
    "Not at the table, Carlos.",  # The Hangover (Alan)
    "You know what they do for fun down here? Crab cakes and football. That's what Maryland does!",  # Wedding Crashers (Chazz Reinhold)
    "You're my boy, Blue!",  # Old School (Frank the Tank)
    "We're going streaking!",  # Old School (Frank)
    "What is this? A center for ants?",  # Zoolander (Derek Zoolander)
    "But why male models?",  # Zoolander (Derek Zoolander)
    "Do the chickens have large talons?",  # Napoleon Dynamite (Napoleon)
    "Vote for Pedro.",  # Napoleon Dynamite (Pedro's campaign)
    "Tina, you fat lard, come get some dinner!",  # Napoleon Dynamite (Kip)
    "Oh, behave!",  # Austin Powers: International Man of Mystery (Austin Powers)
    "Throw me a frickin' bone here.",  # Austin Powers (Dr. Evil)
    "So I got that goin' for me, which is nice.",  # Caddyshack (Carl Spackler)
    "Be the ball.",  # Caddyshack (Ty Webb)
    "Cinderella story. Outta nowhere. A former greenskeeper, now about to become the Masters champion.",  # Caddyshack (Carl Spackler)
    "The price is wrong, bitch.",  # Happy Gilmore (Happy Gilmore)
    "Just tap it in. Give it a little tappy. Tap tap taparoo.",  # Happy Gilmore (Happy Gilmore)
    "T-t-t-today, junior.",  # Billy Madison (the dodgeball ref)
    "Excuse me, I believe you have my stapler.",  # Office Space (Milton)
    "PC Load Letter? What the fuck does that mean?",  # Office Space (Michael Bolton)
    "Sounds like somebody's got a case of the Mondays.",  # Office Space (Nina)
    "I'm not even supposed to be here today!",  # Clerks (Dante)
    "Nobody makes me bleed my own blood. Nobody!",  # Dodgeball (White Goodman)
    "If you can dodge a wrench, you can dodge a ball.",  # Dodgeball (Patches O'Houlihan)
    "Badges? We don't need no stinking badges!",  # Blazing Saddles (Gabby Johnson riff)
    "Surely you can't be serious. I am serious. And don't call me Shirley.",  # Airplane! (Rumack/Striker)
    "Looks like I picked the wrong week to quit sniffing glue.",  # Airplane! (Steve McCroskey)
    "Holy schnikes.",  # Tommy Boy (Tommy)
    "Fat guy in a little coat.",  # Tommy Boy (Tommy)
    "Alright, alright, alright.",  # Dazed and Confused (Wooderson)
    "That's what I love about these high school girls, man. I get older, they stay the same age.",  # Dazed and Confused (Wooderson)
    "Bye, Felicia.",  # Friday (Craig)
    "You got knocked the fuck out!",  # Friday (Smokey)
    "What is your major malfunction?",  # Full Metal Jacket (Gunnery Sgt. Hartman)
    "I bet you could suck a golf ball through a garden hose.",  # Full Metal Jacket (Gunnery Sgt. Hartman)
    "This is my rifle. There are many like it, but this one is mine.",  # Full Metal Jacket (the Rifleman's Creed)
    "Are you gonna bark all day, little doggy, or are you gonna bite?",  # Reservoir Dogs (Mr. Blonde)
    "I'm the guy who does his job. You must be the other guy.",  # The Departed (Billy Costigan)
    "Choose life. Choose a job. Choose a career. Choose a family. Choose a fucking big television.",  # Trainspotting (Renton)
]
