"""Curated movie-quote "wisdom" for the bot.

Raw lines, verbatim — as actually delivered, including character names, film
titles spoken inside the line, specific details, and profanity (some of these
are very R-rated). No attribution suffix is appended; the line stands alone.
Deliberately eclectic across fame, era, origin, register, and how silly/filthy
it gets. Add freely — one short line per entry.
"""

QUOTES = [
    # ── Iconic / pop-culture ──────────────────────────────────────────────────
    "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.",
    "Frankly, my dear, I don't give a damn.",
    "Here's looking at you, kid.",
    "Louis, I think this is the beginning of a beautiful friendship.",
    "Of all the gin joints in all the towns in all the world, she walks into mine.",
    "You had me at hello.",
    "Show me the money!",
    "You complete me.",
    "I'm going to make him an offer he can't refuse.",
    "Leave the gun. Take the cannoli.",
    "Keep your friends close, but your enemies closer.",
    "Say hello to my little friend!",
    "The world is yours.",
    "Nobody puts Baby in a corner.",
    "Toto, I've a feeling we're not in Kansas anymore.",
    "There's no place like home.",
    "I'll have what she's having.",
    "You can't handle the truth!",
    "Show me the way to go home.",
    "Wax on, wax off.",
    "Run, Forrest, run!",
    "Stupid is as stupid does.",
    "My mama always said life was like a box of chocolates. You never know what you're gonna get.",
    "There's no crying in baseball!",
    "You're killin' me, Smalls.",
    "I'm the king of the world!",
    "Why so serious?",
    "Some men just want to watch the world burn.",
    "It's not who I am underneath, but what I do that defines me.",
    "You're gonna need a bigger boat.",
    "Say hello to the bad guy.",
    "Houston, we have a problem.",
    "Carpe diem. Seize the day, boys. Make your lives extraordinary.",
    "What we do in life echoes in eternity.",
    "Are you not entertained?",
    "This is Sparta!",
    "They may take our lives, but they'll never take our freedom!",
    "A man's got to know his limitations.",
    "You talking to me?",
    "I love the smell of napalm in the morning.",
    "The horror... the horror.",
    "Every man dies. Not every man really lives.",
    "Get busy living, or get busy dying.",
    "Hope is a good thing, maybe the best of things, and no good thing ever dies.",

    # ── Noir / classic Hollywood ──────────────────────────────────────────────
    "The stuff that dreams are made of.",
    "All right, Mr. DeMille, I'm ready for my close-up.",
    "I am big. It's the pictures that got small.",
    "Fasten your seatbelts. It's going to be a bumpy night.",
    "Nobody's perfect.",
    "We rob banks.",
    "I coulda been a contender. I coulda been somebody, instead of a bum, which is what I am.",
    "Made it, Ma! Top of the world!",
    "As God is my witness, I'll never be hungry again.",
    "You know how to whistle, don't you, Steve? You just put your lips together and blow.",
    "In Italy, for thirty years under the Borgias, they had warfare, terror, murder and bloodshed, but they produced Michelangelo, Leonardo da Vinci and the Renaissance.",
    "Forget it, Jake. It's Chinatown.",
    "The greed, for lack of a better word, is good.",
    "Attica! Attica!",
    "Rosebud.",

    # ── Sci-fi / fantasy ──────────────────────────────────────────────────────
    "May the Force be with you.",
    "No, I am your father.",
    "Do or do not. There is no try.",
    "I find your lack of faith disturbing.",
    "These aren't the droids you're looking for.",
    "It's a trap!",
    "Never tell me the odds.",
    "I have a bad feeling about this.",
    "So this is how liberty dies. With thunderous applause.",
    "Hello there.",
    "This is the way.",
    "There is no spoon.",
    "I know kung fu.",
    "Welcome to the desert of the real.",
    "Dodge this.",
    "I'll be back.",
    "Come with me if you want to live.",
    "Hasta la vista, baby.",
    "Get away from her, you bitch!",
    "Game over, man! Game over!",
    "In space, no one can hear you scream.",
    "All those moments will be lost in time, like tears in rain.",
    "I've seen things you people wouldn't believe.",
    "Open the pod bay doors, HAL.",
    "My God, it's full of stars.",
    "Life, uh, finds a way.",
    "Clever girl.",
    "Hold onto your butts.",
    "Great Scott!",
    "Roads? Where we're going, we don't need roads.",
    "Nobody calls me chicken.",
    "E.T. phone home.",
    "Get your stinking paws off me, you damned dirty ape!",
    "Welcome to Earth.",
    "The needs of the many outweigh the needs of the few.",
    "Live long and prosper.",
    "One does not simply walk into Mordor.",
    "You shall not pass!",
    "My precious.",
    "Even the smallest person can change the course of the future.",
    "All we have to decide is what to do with the time that is given us.",

    # ── Action cheese ─────────────────────────────────────────────────────────
    "Yippee-ki-yay, motherfucker.",
    "Now I have a machine gun. Ho-ho-ho.",
    "Get to the chopper!",
    "If it bleeds, we can kill it.",
    "I ain't got time to bleed.",
    "Let off some steam, Bennett.",
    "Bond. James Bond.",
    "A martini. Shaken, not stirred.",
    "Do you expect me to talk? No, Mr. Bond, I expect you to die.",
    "I'm your huckleberry.",
    "Say when.",

    # ── Cult / weird ──────────────────────────────────────────────────────────
    "The first rule of Fight Club is: you do not talk about Fight Club.",
    "It's only after we've lost everything that we're free to do anything.",
    "You are not your job. You're not how much money you have in the bank.",
    "The Dude abides.",
    "That rug really tied the room together.",
    "Yeah, well, that's just, like, your opinion, man.",
    "This aggression will not stand, man.",
    "Shut the fuck up, Donny.",
    "Nobody fucks with the Jesus.",
    "Careful, man, there's a beverage here!",
    "I did not hit her, it's not true, it's bullshit, I did not hit her, I did naht. Oh hi Mark.",
    "You're tearing me apart, Lisa!",
    "Fire walk with me.",
    "The owls are not what they seem.",
    "Wake up. You have to wake up.",
    "Every day, once a day, give yourself a present.",
    "Don't dream it, be it.",
    "L-I-V-E, live! Otherwise, you got nothing to talk about in the locker room.",
    "A lot of people don't realize what's really going on. They view life as a bunch of unconnected incidents and things.",
    "We are the music makers, and we are the dreamers of dreams.",
    "So long, and thanks for all the fish.",
    "42.",

    # ── Horror ────────────────────────────────────────────────────────────────
    "They're coming to get you, Barbara.",
    "When there's no more room in hell, the dead will walk the earth.",
    "We have such sights to show you.",
    "It's alive! It's alive! It's alive!",
    "Whatever you do, don't fall asleep.",
    "One, two, Freddy's coming for you.",
    "They're here.",
    "Sometimes dead is better.",
    "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.",
    "The power of Christ compels you!",
    "I see dead people.",
    "Be afraid. Be very afraid.",
    "Man is the warmest place to hide.",
    "You've got red on you.",
    "We all float down here. You'll float too.",
    "Do you like scary movies?",
    "Here's Johnny!",
    "All work and no play makes Jack a dull boy.",
    "We all go a little mad sometimes.",
    "A boy's best friend is his mother.",
    "Listen to them, the children of the night. What music they make.",
    "Get out.",
    "Klaatu barada nikto.",
    "Whatever you do, don't turn around.",
    "It's not the house that's haunted. It's your son.",

    # ── World cinema (translated) ─────────────────────────────────────────────
    "You know what kind of plan never fails? No plan at all.",
    "Once you overcome the one-inch-tall barrier of subtitles, you will be introduced to so many more amazing films.",
    "Life isn't like in the movies. Life is much harder.",
    "Whatever you're going to do, do it fast. Do not hesitate.",
    "Times are hard for dreamers.",
    "Once you've met someone you never really forget them, it just takes a while for your memories to return.",
    "So far, so good. So far, so good. But it's not the fall that matters, it's the landing.",
    "Laugh and the world laughs with you. Weep, and you weep alone.",
    "Even if you're not ready for the day, it cannot always be night.",
    "A story should have a beginning, a middle and an end, but not necessarily in that order.",
    "Cinema is a matter of what's in the frame and what's out.",
    "The farmers have won. We've lost.",
    "In this world, there's a kind of painful progress. Longing for what we've left behind, and dreaming ahead.",
    "Be me, for a little while.",
    "We don't need other worlds. We need mirrors.",
    "Happiness is only real when shared.",
    "The wound is the place where the light enters you.",
    "There is no such thing as goodbye. We'll always be with you.",

    # ── Arthouse / new ────────────────────────────────────────────────────────
    "I drink your milkshake! I drink it up!",
    "I'm finished.",
    "What's the most you ever lost on a coin toss?",
    "Call it, friendo.",
    "You need to be careful. There is greatness in you, but you have to want it.",
    "Not quite my tempo.",
    "There are no two words in the English language more harmful than 'good job.'",
    "A million dollars isn't cool. You know what's cool? A billion dollars.",
    "The past is just a story we tell ourselves.",
    "In moonlight, black boys look blue.",
    "Don't you think maybe they're the same thing? Love and attention?",
    "Do all lovers feel they're inventing something?",
    "Rudeness is merely the expression of fear.",
    "In another life, I would have really liked just doing laundry and taxes with you.",
    "Nothing matters. No point being anything but kind.",
    "Every rejection, every disappointment has led you here, to this moment.",
    "Why'd ya spill yer beans?",
    "Hark!",
    "The bird a nest, the spider a web, man friendship.",
    "You mustn't be afraid to dream a little bigger, darling.",
    "We accept the reality of the world with which we're presented.",

    # ── Comedy / warm ─────────────────────────────────────────────────────────
    "As you wish.",
    "Have fun storming the castle!",
    "Inconceivable! You keep using that word. I do not think it means what you think it means.",
    "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.",
    "Be excellent to each other.",
    "I'm also just a girl, standing in front of a boy, asking him to love her.",
    "The greatest thing you'll ever learn is just to love and be loved in return.",
    "It is not our abilities that show what we truly are. It is our choices.",
    "You is kind. You is smart. You is important.",
    "There's some good in this world, Mr. Frodo, and it's worth fighting for.",
    "Adventure is out there!",
    "Just keep swimming.",
    "To infinity and beyond!",
    "There's a snake in my boot.",
    "Ohana means family. Family means nobody gets left behind or forgotten.",
    "Hakuna matata. It means no worries for the rest of your days.",
    "A person's a person, no matter how small.",
    "Today is the youngest you'll ever be.",

    # ── R-rated / crude / silly ───────────────────────────────────────────────
    "English, motherfucker, do you speak it?",
    "Say 'what' again. Say 'what' again, I dare you, I double dare you, motherfucker.",
    "Zed's dead, baby. Zed's dead.",
    "That is a tasty burger.",
    "Funny how? I mean, funny like I'm a clown? I amuse you?",
    "Go home and get your fuckin' shinebox.",
    "As far back as I can remember, I always wanted to be a gangster.",
    "In this country, you gotta make the money first. Then when you get the money, you get the power.",
    "Come the fuck in, or fuck the fuck off.",
    "Maybe that's what hell is: the entire rest of eternity spent in fuckin' Bruges.",
    "I'm not fuckin' leaving.",
    "The name of the game, move the money from your client's pocket into your pocket.",
    "I am McLovin.",
    "McLovin? What kind of a stupid name is that?",
    "Did we just become best friends? Yup!",
    "So many activities!",
    "I'm kind of a big deal.",
    "Milk was a bad choice.",
    "Sixty percent of the time, it works every time.",
    "I love lamp.",
    "You stay classy, San Diego.",
    "Holy schnikes.",
    "Fat guy in a little coat.",
    "Be the ball.",
    "Cinderella story. Outta nowhere. A former greenskeeper, now about to become the Masters champion.",
    "Badges? We don't need no stinking badges!",
    "Surely you can't be serious. I am serious. And don't call me Shirley.",
    "Looks like I picked the wrong week to quit sniffing glue.",
    "'Tis but a scratch.",
    "We are the knights who say Ni!",
    "Bring out your dead!",
    "I fart in your general direction.",
    "Your mother was a hamster and your father smelt of elderberries.",
    "Sounds like somebody's got a case of the Mondays.",
    "If you can dodge a wrench, you can dodge a ball.",
    "But why male models?",
    "Vote for Pedro.",
    "Tina, you fat lard, come get some dinner!",
    "Gosh!",
    "We're going streaking!",
    "The price is wrong, bitch.",
    "T-t-t-today, junior.",
    "I'm not even supposed to be here today!",
    "Alright, alright, alright.",
    "That's what I love about these high school girls, man. I get older, they stay the same age.",
    "Bye, Felicia.",
    "You got knocked the fuck out!",
    "What is your major malfunction?",
    "This is my rifle. There are many like it, but this one is mine.",
    "Are you gonna bark all day, little doggy, or are you gonna bite?",
    "I'm the guy doin' his job. You must be the other guy.",
    "Choose life.",
    "First you get the money, then you get the power, then you get the woman.",
    "You had me at 'meat tornado.'",
    "That escalated quickly.",
    "Well, that's just, like, the whole point, man.",
]
